const {test} = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {snapshot, check} = require('../helpers/preserved-pack-modules.cjs');
test('E2E accepts only unchanged preinstalled serializer modules outside the private cache', t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(),'pack-preservation-'));
  t.after(() => fs.rmSync(root,{recursive:true,force:true}));
  const directory = path.join(root,'lib/php/pecl/20260925');
  fs.mkdirSync(directory,{recursive:true});
  const module = path.join(directory,'igbinary.so'), file = path.join(root,'before.json');
  fs.writeFileSync(module,'preinstalled serializer');
  snapshot(root,file);
  assert.doesNotThrow(() => check(root,file,module));
  const alias = path.join(root,'Cellar/php/8.5.11_1/pecl');
  fs.mkdirSync(path.dirname(alias),{recursive:true});
  fs.symlinkSync(path.join(root,'lib/php/pecl'),alias);
  assert.doesNotThrow(() => check(root,file,path.join(alias,'20260925/igbinary.so')));
  fs.writeFileSync(path.join(root,'igbinary.so'),'unmanaged serializer');
  assert.throws(() => check(root,file,path.join(root,'igbinary.so')),/not a preservable/);
  fs.writeFileSync(module,'unexpected replacement');
  assert.throws(() => check(root,file,module),/not preserved/);
  const added = path.join(directory,'msgpack.so');fs.writeFileSync(added,'new');
  assert.throws(() => check(root,file,added),/not preserved/);
  assert.throws(() => check(root,file,path.join(directory,'memcached.so')),/not a preservable/);
  fs.unlinkSync(module);fs.symlinkSync('msgpack.so',module);snapshot(root,file);
  assert.doesNotThrow(() => check(root,file,module));
  fs.unlinkSync(module);fs.symlinkSync(added,module);
  assert.throws(() => check(root,file,module),/not preserved/);
});
