#!/usr/bin/env bash
# Generated by scripts/installer/generate-install.cjs. Do not edit.

php_darwin_read_config() {
  case "$1" in
    package.json) cat <<'PHP_DARWIN_CONFIG'
{
  "current_version": "8.5",
  "extension_tap": "shivammathur/extensions",
  "extension_tap_branch": "main",
  "extension_tap_repository": "https://github.com/shivammathur/homebrew-extensions",
  "release_repository": "shivammathur/php-darwin",
  "tap": "shivammathur/php",
  "tap_branch": "main",
  "tap_repository": "https://github.com/shivammathur/homebrew-php",
  "tap_snapshot": "var/php-darwin/homebrew-php",
  "artifact_mirror": "https://artifacts.php-darwin.setup-php.com",
  "artifact_bucket": "php-darwin",
  "extension_release": "extensions"
}
PHP_DARWIN_CONFIG
      ;;
    transfers.json) cat <<'PHP_DARWIN_CONFIG'
{
  "attempts": 3,
  "connect_timeout": 5,
  "retry_delay": 1,
  "retry_after_max": 30,
  "metadata": {
    "timeout": 30,
    "max_bytes": 2000000
  },
  "archive": {
    "timeout": 300,
    "speed_time": 10,
    "speed_limit": 1024
  }
}
PHP_DARWIN_CONFIG
      ;;
    platforms.json) cat <<'PHP_DARWIN_CONFIG'
{
  "arm64": {
    "build_runner": "macos-14",
    "brew_prefix": "/opt/homebrew",
    "minimum_macos": 14,
    "platform_key": "arm64_sonoma",
    "test_runners": ["macos-14", "macos-15", "macos-26", "macos-latest"]
  },
  "x86_64": {
    "build_runner": "macos-15-intel",
    "brew_prefix": "/usr/local",
    "minimum_macos": 15,
    "platform_key": "sequoia",
    "test_runners": ["macos-15-intel", "macos-26-intel"]
  }
}
PHP_DARWIN_CONFIG
      ;;
    variants) cat <<'PHP_DARWIN_CONFIG'
# build thread-safety
release nts
release zts
debug nts
debug zts
PHP_DARWIN_CONFIG
      ;;
    versions) cat <<'PHP_DARWIN_CONFIG'
# channel version
stable 5.6
stable 7.0
stable 7.1
stable 7.2
stable 7.3
stable 7.4
stable 8.0
stable 8.1
stable 8.2
stable 8.3
stable 8.4
stable 8.5
nightly 8.6
nightly 8.7
PHP_DARWIN_CONFIG
      ;;
    release-manifest.json) cat <<'PHP_DARWIN_MANIFEST'
{}
PHP_DARWIN_MANIFEST
      ;;
    *) return 1 ;;
  esac
}

php_darwin_package_config() {
  jq -er --arg key "$1" '.[$key]' < <(php_darwin_read_config package.json) || \
    php_darwin_die "package configuration is missing: $1"
}

php_darwin_die() {
  if [ -n "${PHP_DARWIN_PHASE:-}" ]; then
    printf 'php-darwin: %s failed: %s\n' "$PHP_DARWIN_PHASE" "$*" >&2
  else
    printf 'php-darwin: %s\n' "$*" >&2
  fi
  exit 1
}

php_darwin_normalize_arch() {
  case "${1:-$(uname -m)}" in
    arm64|aarch64) printf 'arm64\n' ;;
    x86_64|amd64) printf 'x86_64\n' ;;
    *) php_darwin_die "unsupported architecture: ${1:-<empty>}" ;;
  esac
}

php_darwin_validate_version() {
  local requested_version=${1:-}
  local configured_channel
  local configured_version
  local extra

  php_darwin_load_versions || php_darwin_die 'invalid PHP version configuration'
  while read -r configured_channel configured_version extra; do
    if [ "$configured_version" = "$requested_version" ]; then
      return 0
    fi
  done <<< "$php_darwin_configured_versions_data"
  php_darwin_die "unsupported PHP version: ${requested_version:-<empty>}"
}

php_darwin_load_versions() {
  local channel
  local configured=
  local extra
  local seen=
  local version

  [ "${php_darwin_configured_versions_data+x}" != x ] || return 0
  while read -r channel version extra; do
    [ -n "$channel" ] || continue
    case "$channel" in \#*) continue ;; stable|nightly) ;; *) return 1 ;; esac
    [ -n "$version" ] && [ -z "$extra" ] && [[ "$version" =~ ^[0-9]+\.[0-9]+$ ]] || return 1
    case " $seen " in *" $version "*) return 1 ;; esac
    seen="$seen $version"
    configured=${configured:+"$configured"$'\n'}"$channel $version"
  done < <(php_darwin_read_config versions)
  [ -n "$configured" ] || return 1
  php_darwin_configured_versions_data=$configured
}

php_darwin_validate_build() {
  case "${1:-}" in
    release|debug) ;;
    *) php_darwin_die "build must be release or debug: ${1:-<empty>}" ;;
  esac
}

php_darwin_validate_ts() {
  case "${1:-}" in
    nts|zts) ;;
    *) php_darwin_die "thread safety must be nts or zts: ${1:-<empty>}" ;;
  esac
}

php_darwin_asset() {
  local version=$1
  local version_major
  local version_minor
  local build=${2:-release}
  local ts=${3:-nts}
  local arch

  IFS=. read -r version_major version_minor _ <<< "$version"
  php_darwin_validate_version "$version_major.$version_minor"
  php_darwin_validate_build "$build"
  php_darwin_validate_ts "$ts"
  arch=$(php_darwin_normalize_arch "${4:-}") || return 1
  printf 'php_%s-%s-%s+darwin_%s.tar.zst\n' "$version" "$ts" "$build" "$arch"
}

php_darwin_version_channel() {
  local requested_version=${1:-}
  local configured_channel
  local configured_version
  local extra

  php_darwin_load_versions || php_darwin_die 'invalid PHP version configuration'
  while read -r configured_channel configured_version extra; do
    if [ "$configured_version" = "$requested_version" ]; then
      printf '%s\n' "$configured_channel"
      return 0
    fi
  done <<< "$php_darwin_configured_versions_data"
  php_darwin_die "unsupported PHP version: ${requested_version:-<empty>}"
}

php_darwin_release_manifest_url() {
  local release_repository=$1
  local version=$2

  [[ "$release_repository" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] || return 1
  php_darwin_validate_version "$version"
  printf 'https://github.com/%s/releases/download/php-%s/php-%s-manifest.json?cache=%s\n' \
    "$release_repository" "$version" "$version" "$(date +%s)"
}

php_darwin_fetch_release_manifest() {
  local destination=$3
  local manifest_url
  local request_status=000
  local mirror_url
  local urls=()

  if [ -n "${4:-}" ]; then
    manifest_url=$4
  else
    manifest_url=$(php_darwin_release_manifest_url "$1" "$2") || return 1
  fi
  urls+=("$manifest_url")
  if [ -z "${4:-}" ] || [ -n "${PHP_DARWIN_MIRROR_URL:-}" ]; then
    mirror_url=$(php_darwin_release_mirror "$1" "$2") || return 1
    [ -z "$mirror_url" ] || urls+=("$mirror_url/php-$2-manifest.json")
    if [ -n "$mirror_url" ] && [ "${PHP_DARWIN_PREFER_MIRROR:-false}" = true ]; then
      urls=("$mirror_url/php-$2-manifest.json" "$manifest_url")
    fi
  fi
  for manifest_url in "${urls[@]}"; do
    if ! request_status=$(php_darwin_request_release "$manifest_url" "$destination"); then
      request_status=000
      continue
    fi
    if [ "$request_status" = 200 ]; then
      if php_darwin_validate_release_manifest "$destination" "$2" >/dev/null 2>&1; then
        printf '200\n'
        return 0
      fi
      printf 'php-darwin: invalid release manifest from %s\n' "$manifest_url" >&2
      request_status=000
    fi
  done
  printf '%s\n' "$request_status"
}

php_darwin_release_mirror() {
  local mirror=${PHP_DARWIN_MIRROR_URL-}
  if [ "${PHP_DARWIN_MIRROR_URL+x}" != x ] && [ "$1" = "$(php_darwin_package_config release_repository)" ]; then
    mirror=$(php_darwin_package_config artifact_mirror) || return 1
  fi
  [ -n "$mirror" ] || return 0
  printf '%s/php-%s\n' "${mirror%/}" "$2"
}

php_darwin_request_release() {
  local status
  local result=0
  local range=()
  local attempt=1 attempts connect_timeout delay retry_after retry_delay retry_after_max policy
  policy=$(php_darwin_read_config transfers.json | jq -er '[.attempts,.connect_timeout,.retry_delay,.retry_after_max,.metadata.timeout,.archive.speed_time,.archive.speed_limit] | @tsv') || return 1
  local metadata_timeout speed_time speed_limit
  IFS=$'\t' read -r attempts connect_timeout retry_delay retry_after_max metadata_timeout speed_time speed_limit <<< "$policy"
  local headers=(--dump-header "$2.headers")
  [ -z "${6:-}" ] || range=(--range "$6-")

  # Retry every failed transfer on either origin, with a fixed attempt limit.
  # Each retry replaces its output at the same requested range offset;
  # the archive caller verifies the complete assembled SHA before extraction.
  while :; do
    result=0
    if [ "$attempts" -gt 1 ]; then : > "$2.headers" || return 1; fi
    status=$(curl --retry 0 --connect-timeout "$connect_timeout" --speed-time "${4:-$speed_time}" --speed-limit "${3:-$speed_limit}" \
      --max-time "${5:-$metadata_timeout}" ${range[@]+"${range[@]}"} ${headers[@]+"${headers[@]}"} \
      -fsSL -w '%{http_code}' "$1" -o "$2") || result=$?
    if [ "$result" -ne 0 ] || { [ "$status" != 200 ] && [ "$status" != 206 ]; }; then
      printf 'php-darwin: download failed (curl %s, HTTP %s): %s\n' \
        "$result" "${status:-000}" "$1" >&2
    fi
    [ "$attempt" -lt "$attempts" ] || break
    if [ "$result" -eq 0 ] && { [ "$status" = 200 ] || [ "$status" = 206 ]; }; then break; fi
    delay=$((retry_delay << (attempt - 1)))
    retry_after=$(awk 'tolower($1) == "retry-after:" {gsub(/\r/, "", $2); value=$2} END {print value}' "$2.headers" 2>/dev/null) || retry_after=
    if [[ "$retry_after" =~ ^[0-9]{1,6}$ ]]; then
      retry_after=$((10#$retry_after))
      [ "$retry_after" -le "$retry_after_max" ] || retry_after=$retry_after_max
      [ "$retry_after" -le "$delay" ] || delay=$retry_after
    fi
    printf 'php-darwin: retrying transfer %s/%s in %ss\n' "$((attempt + 1))" "$attempts" "$delay" >&2
    sleep "$delay"
    attempt=$((attempt + 1))
  done
  [ "$attempts" -eq 1 ] || rm -f "$2.headers"
  # HTTP errors are classified by the caller (especially retired 404 assets).
  # --fail stops at their headers instead of downloading a slow error body.
  if [ "$result" -eq 22 ] && [[ "$status" =~ ^[45][0-9][0-9]$ ]]; then
    result=0
  fi
  printf '%s\n' "${status:-000}"
  return "$result"
}

php_darwin_sha256() {
  local hash_output

  if [ -x /usr/bin/openssl ]; then
    hash_output=$(/usr/bin/openssl dgst -sha256 "$1") || return 1
    hash_output=${hash_output##* }
  elif command -v sha256sum >/dev/null 2>&1; then
    hash_output=$(sha256sum "$1") || return 1
  else
    hash_output=$(shasum -a 256 "$1") || return 1
  fi
  printf '%s\n' "${hash_output%% *}"
}

php_darwin_checksum_from_file() {
  local checksum_file=$1
  local asset=$2

  [ -f "$checksum_file" ] || {
    printf 'Checksum file not found: %s\n' "$checksum_file" >&2
    return 1
  }
  awk -v name="$asset" '
    !NF { next }
    NF != 2 || $1 !~ /^[0-9a-f]+$/ || length($1) != 64 { invalid=1; next }
    $2 == name { matches++; hash=$1 }
    END {
      if (invalid || matches != 1) exit 1
      print hash
    }
  ' "$checksum_file"
}
# Select and authenticate an immutable archive before executing its installer.
version=${1:-$(php_darwin_package_config current_version)}
build=${2:-release}
ts=${3:-nts}
local_archive=${4:-}
extensions_input=${5-${PHP_DARWIN_EXTENSIONS:-${INPUT_EXTENSIONS:-}}}
[ "$(uname -s)" = Darwin ] || php_darwin_die 'the cache installer only supports macOS'
for required in brew curl jq tar zstd; do
  command -v "$required" >/dev/null 2>&1 || php_darwin_die "$required is required"
done
arch=$(php_darwin_normalize_arch "$(uname -m)") || exit 1
php_darwin_validate_version "$version"
php_darwin_validate_build "$build"
php_darwin_validate_ts "$ts"
asset=$(php_darwin_asset "$version" "$build" "$ts" "$arch") || exit 1
channel=$(php_darwin_version_channel "$version") || exit 1
release_repository=${PHP_DARWIN_RELEASE_REPOSITORY:-$(php_darwin_package_config release_repository)}
[[ "$release_repository" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] || php_darwin_die 'invalid release repository'
tmp_dir=$(mktemp -d "${RUNNER_TEMP:-/tmp}/php-darwin-bootstrap.XXXXXX") || exit 1
extension_dir="$tmp_dir/extensions"
extension_prefetch_pid=
installer_pid=
cleanup() {
  local status=$?
  trap - EXIT HUP INT TERM
  # The transaction handles rollback before its bootstrap removes staging.
  if [ -n "$installer_pid" ]; then kill -TERM "$installer_pid" 2>/dev/null || true; wait "$installer_pid" || true; fi
  if [ -n "$extension_prefetch_pid" ]; then kill -TERM "$extension_prefetch_pid" 2>/dev/null || true; wait "$extension_prefetch_pid" || true; fi
  rm -rf "$tmp_dir"
  exit "$status"
}
trap cleanup EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM

# Validate only the selected identity. Full release/provenance checks run before publication.
php_darwin_validate_release_manifest() {
  jq -e --arg version "$version" --arg arch "$arch" --arg build "$build" --arg ts "$ts" --arg asset "$asset" '
    select(.schema == 1 and .php_version == $version) |
    [.assets[] | select(.architecture == $arch and .build == $build and .thread_safety == $ts)] |
    select(length == 1) | .[0] | select(.name == $asset and
      (.sha256 | type == "string" and test("^[a-f0-9]{64}$")) and
      (.bytes | type == "number" and floor == . and . > 0) and
      (.minimum_macos | type == "number" and floor == . and . > 0) and
      (.download | type == "string" and test("^[A-Za-z0-9_.+-]+\\.tar\\.zst$")))
  ' "$1" >/dev/null
}
php_darwin_use_release_manifest() {
  php_darwin_validate_release_manifest "$1" || return 1
  local values
  values=$(jq -er --arg asset "$asset" '.assets[] | select(.name == $asset) | [.sha256,.download,.bytes,.minimum_macos] | @tsv' "$1") || return 1
  IFS=$'\t' read -r expected_hash manifest_download_asset manifest_archive_bytes minimum_macos <<< "$values"
  [ "$manifest_download_asset" = "${asset%.tar.zst}.$expected_hash.tar.zst" ] || return 1
  [ "$(sw_vers -productVersion | cut -d. -f1)" -ge "$minimum_macos" ] || php_darwin_die 'archive requires newer macOS'
}
php_darwin_refresh_release_manifest() {
  manifest_url=${PHP_DARWIN_MANIFEST_URL:-}
  [ -n "$manifest_url" ] || manifest_url=$(php_darwin_release_manifest_url "$release_repository" "$version") || \
    php_darwin_die 'could not construct the release manifest URL'
  manifest_status=$(php_darwin_fetch_release_manifest "$release_repository" "$version" \
    "$release_manifest" "${PHP_DARWIN_MANIFEST_URL:-}") || php_darwin_die "could not request $manifest_url"
  [ "$manifest_status" = 200 ] || \
    php_darwin_die "could not fetch the PHP $version release manifest (HTTP $manifest_status)"
  php_darwin_use_release_manifest "$release_manifest" || \
    php_darwin_die 'release manifest did not match the requested PHP version'
  manifest_from_embedded=false
}

php_darwin_download_release_archive() {
  local archive_http_status
  local mirror_url
  local urls=()
  local destination transfer_policy transfer_limit transfer_speed transfer_timeout
  transfer_policy=$(php_darwin_read_config transfers.json | jq -er '[.archive.speed_limit,.archive.speed_time,.archive.timeout] | @tsv') || return 1
  IFS=$'\t' read -r transfer_limit transfer_speed transfer_timeout <<< "$transfer_policy"
  local resume_bytes='' request_result received_bytes

  release_archive_error=
  release_url=${PHP_DARWIN_RELEASE_URL:-https://github.com/$release_repository/releases/download/php-$version/$manifest_download_asset}
  urls+=("$release_url")
  if [ -z "${PHP_DARWIN_RELEASE_URL:-}" ] || [ -n "${PHP_DARWIN_MIRROR_URL:-}" ]; then
    mirror_url=$(php_darwin_release_mirror "$release_repository" "$version") || return 1
    [ -z "$mirror_url" ] || urls+=("$mirror_url/$manifest_download_asset")
    if [ -n "$mirror_url" ] && [ "${PHP_DARWIN_PREFER_MIRROR:-false}" = true ]; then
      urls=("$mirror_url/$manifest_download_asset" "$release_url")
    fi
  fi
  release_archive_error=not-found
  for release_url in "${urls[@]}"; do
    destination=$archive
    [ -z "$resume_bytes" ] || destination="$archive.remaining"
    request_result=0
    archive_http_status=$(php_darwin_request_release "$release_url" "$destination" \
      "$transfer_limit" "$transfer_speed" "$transfer_timeout" "$resume_bytes") || request_result=$?
    if [ "$request_result" -ne 0 ]; then
      [ "$release_archive_error" = checksum ] || release_archive_error=download
      if [ "$archive_http_status" = 200 ] && [ -s "$archive" ] && [ -z "$resume_bytes" ]; then
        received_bytes=$(wc -c < "$archive" | tr -d '[:space:]')
        if [ "$received_bytes" -lt "$manifest_archive_bytes" ]; then
          # A known incomplete prefix cannot match the digest. Start the mirror
          # immediately and authenticate the complete combined archive below.
          resume_bytes=$received_bytes
        elif [ "$received_bytes" -eq "$manifest_archive_bytes" ]; then
          # A timeout can arrive after the last byte. Still require its digest;
          # a corrupt complete response must restart at the next origin.
          php_darwin_start_archive_hash "$archive"
          php_darwin_wait_for_archive_hash
          if [ "$actual_hash" = "$expected_hash" ]; then release_archive_error=; return 0; fi
          release_archive_error=checksum
        fi
      fi
      continue
    fi
    if [ -n "$resume_bytes" ]; then
      case "$archive_http_status" in
        206) cat "$destination" >> "$archive" || return 1 ;;
        # Range is optional at the origin. A full response replaces the prefix.
        200) mv "$destination" "$archive" || return 1 ;;
      esac
    fi
    if [ "$archive_http_status" != 200 ] && \
      { [ "$archive_http_status" != 206 ] || [ -z "$resume_bytes" ]; }; then
      if [ "$archive_http_status" != 404 ] && [ "$release_archive_error" != checksum ]; then
        release_archive_error=download
      fi
      continue
    fi
    php_darwin_start_archive_hash "$archive"
    php_darwin_wait_for_archive_hash
    if [ "$actual_hash" = "$expected_hash" ]; then
      release_archive_error=
      return 0
    fi
    printf 'php-darwin: checksum mismatch from %s; trying the next origin\n' "$release_url" >&2
    release_archive_error=checksum
    resume_bytes=
  done
  return 1
}


php_darwin_start_archive_hash() { actual_hash=$(php_darwin_sha256 "$1") || exit 1; }
php_darwin_wait_for_archive_hash() { :; }
# Download packs concurrently with PHP; no PHP files or Homebrew state are changed here.
if [ -n "$extensions_input" ] && extension_node=$(command -v "${PHP_DARWIN_NODE:-node}"); then
  mkdir -p "$extension_dir" || exit 1
cat > "$extension_dir/prefetch.cjs" <<'PHP_DARWIN_PREFETCH'
const fs = require('node:fs'), fsp = fs.promises, path = require('node:path'), crypto = require('node:crypto');
const {pipeline} = require('node:stream/promises');
const {Readable} = require('node:stream');
const hex = /^[a-f0-9]{64}$/;
const configuration = {"versions":["5.6","7.0","7.1","7.2","7.3","7.4","8.0","8.1","8.2","8.3","8.4","8.5","8.6","8.7"],"cached":[{"name":"xdebug"},{"name":"pcov"}],"pack_versions":{"swoole":["5.6","7.0","7.1","7.2","7.3","7.4","8.0","8.1","8.2","8.3","8.4","8.5"]},"packs":{"imagick":[{"name":"imagick"}],"mongodb":[{"name":"mongodb"}],"memcached":[{"name":"igbinary"},{"name":"msgpack"},{"name":"memcached","priority":30}],"swoole":[{"name":"swoole"}]},"headers":{"memcached":{"igbinary":"igbinary.h","msgpack":"php_msgpack.h"}},"runtime_resources":{"cyrus-sasl":{"SASL_PATH":"/lib/sasl2$"},"imagemagick":{"MAGICK_CODER_MODULE_PATH":"/modules-[^/]+/coders$","MAGICK_FILTER_MODULE_PATH":"/modules-[^/]+/filters$","MAGICK_CONFIGURE_PATH":"/(?:etc|share)/ImageMagick-[^/]+$"}}};
const platforms = {"arm64":{"build_runner":"macos-14","brew_prefix":"/opt/homebrew","minimum_macos":14,"platform_key":"arm64_sonoma","test_runners":["macos-14","macos-15","macos-26","macos-latest"]},"x86_64":{"build_runner":"macos-15-intel","brew_prefix":"/usr/local","minimum_macos":15,"platform_key":"sequoia","test_runners":["macos-15-intel","macos-26-intel"]}};
const packageConfig = {"current_version":"8.5","extension_tap":"shivammathur/extensions","extension_tap_branch":"main","extension_tap_repository":"https://github.com/shivammathur/homebrew-extensions","release_repository":"shivammathur/php-darwin","tap":"shivammathur/php","tap_branch":"main","tap_repository":"https://github.com/shivammathur/homebrew-php","tap_snapshot":"var/php-darwin/homebrew-php","artifact_mirror":"https://artifacts.php-darwin.setup-php.com","artifact_bucket":"php-darwin","extension_release":"extensions"};
const buildConfig = {"compression_level":19,"compression_long":27,"max_archive_bytes":{"5.6":180000000,"7.0":180000000,"7.1":180000000,"7.2":180000000,"7.3":180000000,"7.4":180000000,"8.0":180000000,"8.1":180000000,"8.2":180000000,"8.3":180000000,"8.4":180000000,"8.5":180000000,"8.6":180000000,"8.7":180000000},"extension_max_archive_bytes":180000000,"repack_concurrency":2};
const transfers = {"attempts":3,"connect_timeout":5,"retry_delay":1,"retry_after_max":30,"metadata":{"timeout":30,"max_bytes":2000000},"archive":{"timeout":300,"speed_time":10,"speed_limit":1024}};
const variants = [["release","nts"],["release","zts"],["debug","nts"],["debug","zts"]];
const packs = {"imagick":["imagick"],"mongodb":["mongodb"],"memcached":["igbinary","msgpack","memcached"],"swoole":["swoole"]};
const origins = ["https://github.com/shivammathur/php-darwin/releases/download/extensions","https://artifacts.php-darwin.setup-php.com/extensions"];
function supportsPack(name, version) {
  return Object.hasOwn(packs, name) && configuration.versions.includes(version) &&
    (configuration.pack_versions?.[name] || configuration.versions).includes(version);
}
function safePath(value) {
  return typeof value === 'string' && value.length > 0 && !/[\x00-\x1f\x7f\\]/.test(value) &&
    !value.startsWith('/') && value.split('/').every(part => part && part !== '.' && part !== '..');
}
function validateContext(context) {
  if (!context || !configuration.versions.includes(context.php_version) ||
      !Object.hasOwn(platforms, context.architecture) ||
      !variants.some(([build, ts]) => build === context.build && ts === context.thread_safety)) {
    throw new Error('Unsupported extension cache configuration');
  }
  return context;
}
function key(entry) {
  validateContext(entry);
  if (!Object.hasOwn(packs, entry.name)) throw new Error('Unknown extension pack');
  if (!supportsPack(entry.name, entry.php_version)) throw new Error('Unsupported PHP version for extension pack');
  return [entry.name, entry.php_version, entry.build, entry.thread_safety, entry.architecture].join('-');
}
function validateEntry(entry) {
  key(entry);
  if (entry.schema !== 1 || !hex.test(entry.sha256) || !hex.test(entry.inputs_sha256) ||
      !/^[0-9]{8}$/.test(entry.php_api) ||
      !Number.isInteger(entry.bytes) || entry.bytes < 1 || entry.bytes > buildConfig.extension_max_archive_bytes ||
      !Number.isInteger(entry.minimum_macos) || entry.minimum_macos < platforms[entry.architecture].minimum_macos ||
      entry.file !== `${key(entry)}-${entry.sha256}.tar.zst`) throw new Error('Invalid extension cache metadata');
  return entry;
}
async function download(name, destination, { sha256, bytes, bases = origins,
  fresh = false, sleep = ms => new Promise(resolve => setTimeout(resolve, ms)) } = {}) {
  if (!safePath(name) || name.includes('/')) throw new Error('Invalid download name');
  let lastError;
  const missing = new Set();
  for (const base of bases) {
    const attempts = transfers.attempts;
    for (let attempt = 1; attempt <= attempts; attempt++) {
      const temporary = `${destination}.partial`;
      try {
        missing.delete(base);
        // Give archives time to finish on either origin; metadata stays bounded.
        const response = await fetch(`${base}/${name}${fresh ? `?refresh=${Date.now()}` : ''}`, { signal: AbortSignal.timeout((bytes ? transfers.archive.timeout : transfers.metadata.timeout) * 1000) });
        if (!response.ok || !response.body) {
          await response.body?.cancel();
          const retryAfter = response.headers.get('retry-after');
          if ([404, 410].includes(response.status)) missing.add(base);
          throw Object.assign(new Error(`HTTP ${response.status}`), {
            retryAfter: /^\d{1,6}$/.test(retryAfter || '') ? Math.min(transfers.retry_after_max, Number(retryAfter)) : 0
          });
        }
        let received = 0;
        const hash = crypto.createHash('sha256');
        const limit = bytes || transfers.metadata.max_bytes;
        await pipeline(Readable.fromWeb(response.body), async function* (source) {
          for await (const chunk of source) {
            received += chunk.length;
            if (received > limit) throw new Error('Download exceeds expected size');
            hash.update(chunk);
            yield chunk;
          }
        }, fs.createWriteStream(temporary, { flags: 'wx', mode: 0o600 }));
        if ((bytes && received !== bytes) || (sha256 && hash.digest('hex') !== sha256)) {
          throw new Error('Extension archive checksum/size mismatch');
        }
        await fsp.rename(temporary, destination);
        return;
      } catch (error) {
        lastError = error;
        await fsp.rm(temporary, { force: true });
        if (attempt === attempts) break;
        const delay = Math.max(transfers.retry_delay * 2 ** (attempt - 1), error.retryAfter || 0);
        console.warn(`Extension download retry ${attempt + 1}/${attempts} in ${delay}s: ${error.message}`);
        await sleep(delay * 1000);
      }
    }
  }
  throw Object.assign(new Error(`Could not download ${name}: ${lastError.message}`), { retired: missing.size === bases.length });
}
async function prefetch(directory, context, requested, options = {}) {
  validateContext(context);
  if (!requested.length || requested.some(name => !Object.hasOwn(packs, name))) throw new Error('Invalid requested extensions');
  const names = [...new Set(requested)].filter(name => supportsPack(name, context.php_version));
  if (!names.length) return [];
  await fsp.mkdir(directory, { recursive: true, mode: 0o700 });
  const manifestPath = path.join(directory, 'manifest.json');
  await download(`extensions-${context.php_version}-manifest.json`, manifestPath, options);
  const manifest = JSON.parse(await fsp.readFile(manifestPath, 'utf8'));
  if (manifest.schema !== 1 || !Array.isArray(manifest.assets)) throw new Error('Invalid extension manifest');
  let refreshed;
  const select = (manifest, name) => {
    if (manifest.schema !== 1 || !Array.isArray(manifest.assets)) throw new Error('Invalid extension manifest');
    const candidates = manifest.assets.filter(entry => entry.name === name &&
      Object.entries(context).every(([field, value]) => entry[field] === value));
    if (candidates.length !== 1) throw new Error(`No unique compatible archive for ${name}`);
    return validateEntry(candidates[0]);
  };
  const results = await Promise.allSettled(names.map(async name => {
    let entry = select(manifest, name);
    console.log(`Downloading ${name} cache (${entry.bytes} bytes)`);
    try {
      await download(entry.file, path.join(directory, entry.file), { ...options, sha256: entry.sha256, bytes: entry.bytes });
    } catch (error) {
      if (!error.retired) throw error;
      // Publication can retire the archive after this install read its manifest.
      // Refresh once, shared across packs; retain exact context and checksums.
      refreshed ||= (async () => {
        await download(`extensions-${context.php_version}-manifest.json`, manifestPath, { ...options, fresh: true });
        return JSON.parse(await fsp.readFile(manifestPath, 'utf8'));
      })();
      const replacement = select(await refreshed, name);
      if (replacement.file === entry.file) throw error;
      entry = replacement;
      await download(entry.file, path.join(directory, entry.file), { ...options, sha256: entry.sha256, bytes: entry.bytes });
    }
    await fsp.writeFile(path.join(directory, `${name}.json`), JSON.stringify(entry));
    try {
      // Use independent processes so extraction cannot block other downloads.
      // This overlaps PHP setup without loading or changing the active PHP.
      await (options.prepare || prepareDownloaded)(directory, name);
    } catch (error) {
      await fsp.rm(path.join(directory, `${name}.json`), { force: true });
      throw error;
    }
    return name;
  }));
  results.forEach((result, index) => {
    if (result.status === 'rejected') console.warn(`Extension cache ${names[index]}: ${result.reason.message}`);
  });
  return results.filter(result => result.status === 'fulfilled').map(result => result.value);
}
function selectRequested(input, candidates = packs) {
  const tokens = String(input).split(',').map(value => value.trim().toLowerCase().replace(/^(:)?php[-_]/, '$1'));
  return Object.entries(candidates).filter(([name, modules]) => tokens.includes(name) &&
    !modules.some(module => tokens.some(token => token === `:${module}` ||
      token.startsWith(`${module}-`) || token.startsWith(`${module}@`))))
    .map(([name]) => name);
}
(async () => {
  const [directory, input, php_version, build, thread_safety, architecture] = process.argv.slice(2);
  const names = selectRequested(input);
  fs.writeFileSync(path.join(directory, 'requested.txt'), names.join('\n'));
  if (names.length) await prefetch(directory, {php_version, build, thread_safety, architecture}, names, {prepare: async () => {}});
})().catch(error => {console.error(error.message); process.exitCode = 1;});
PHP_DARWIN_PREFETCH

  (
    "$extension_node" "$extension_dir/prefetch.cjs" "$extension_dir" "$extensions_input" "$version" "$build" "$ts" "$arch" > "$extension_dir/prefetch.log" 2>&1 &
    worker=$!
    trap 'kill -TERM "$worker" 2>/dev/null; wait "$worker"; exit 143' TERM INT HUP
    prefetch_status=0
    wait "$worker" || prefetch_status=$?
    printf '%s\n' "$prefetch_status" > "$extension_dir/complete"
  ) &
  extension_prefetch_pid=$!
fi
archive="$tmp_dir/$asset"
release_manifest="$tmp_dir/manifest.json"
manifest_from_embedded=false
if [ -n "$local_archive" ]; then
  archive=$(cd "$(dirname "$local_archive")" && pwd)/$(basename "$local_archive")
  expected_hash=$(php_darwin_checksum_from_file "$archive.sha256" "$asset") || php_darwin_die 'missing local archive checksum'
  [ "$(php_darwin_sha256 "$archive")" = "$expected_hash" ] || php_darwin_die 'local archive checksum mismatch'
else
  php_darwin_read_config release-manifest.json > "$release_manifest"
  if php_darwin_use_release_manifest "$release_manifest"; then manifest_from_embedded=true; else php_darwin_refresh_release_manifest; fi
  if ! php_darwin_download_release_archive; then
    if [ "$manifest_from_embedded" = true ] && [ "$release_archive_error" = not-found ]; then
      php_darwin_refresh_release_manifest
      php_darwin_download_release_archive || php_darwin_die 'could not download the current PHP archive'
    else php_darwin_die "could not download PHP archive: $release_archive_error"; fi
  fi
fi
# Extract only the fixed controller member to stdout in a private directory.
# No archive paths are written to the host until after complete authentication.
case "$(tar --version)" in *bsdtar*) options=(-q);; *) options=(--occurrence=1);; esac
zstd -qdc "$archive" 2> "$tmp_dir/zstd.log" | tar -xOf - "${options[@]}" var/php-darwin/installer/install.sh > "$tmp_dir/install.sh"
statuses=("${PIPESTATUS[@]}")
if [ "${statuses[0]}" -eq 70 ] && grep -Eq '^zstd: error 70 : Write error : .*Broken pipe *$' "$tmp_dir/zstd.log"; then statuses[0]=141; fi
[ "${statuses[1]}" -eq 0 ] && { [ "${statuses[0]}" -eq 0 ] || [ "${statuses[0]}" -eq 141 ]; } && [ -s "$tmp_dir/install.sh" ] || php_darwin_die 'archive has no readable packaged installer'
bash -n "$tmp_dir/install.sh" || php_darwin_die 'invalid packaged installer'
PHP_DARWIN_PREFETCH_DIR="${extension_prefetch_pid:+$extension_dir}" PHP_DARWIN_PREFETCH_PID="$extension_prefetch_pid" \
  bash "$tmp_dir/install.sh" "$version" "$build" "$ts" "$archive" "$extensions_input" &
installer_pid=$!
status=0
wait "$installer_pid" || status=$?
installer_pid=
exit "$status"
